spring:
  datasource:
    url: jdbc:mysql://47.98.40.154:3306/lazyNote?characterEncoding=utf-8&useSSL=false
    username: root
    password: Zsy960914.
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true